/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as ExplainRouteImport } from './routes/explain'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FactsRouteImport } from './routes/facts'
import { Route as FoodRouteImport } from './routes/food'
import { Route as FoodLabelsRouteImport } from './routes/food-labels'
import { Route as GreyMarketRouteImport } from './routes/grey-market'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainRoute = ExplainRouteImport.update({
  id: '/explain',
  path: '/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FactsRoute = FactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodLabelsRoute = FoodLabelsRouteImport.update({
  id: '/food-labels',
  path: '/food-labels',
  getParentRoute: () => rootRouteImport,
} as any)
const GreyMarketRoute = GreyMarketRouteImport.update({
  id: '/grey-market',
  path: '/grey-market',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/emergency': typeof EmergencyRoute
  '/explain': typeof ExplainRoute
  '/explore': typeof ExploreRoute
  '/facts': typeof FactsRoute
  '/food': typeof FoodRoute
  '/food-labels': typeof FoodLabelsRoute
  '/grey-market': typeof GreyMarketRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/emergency': typeof EmergencyRoute
  '/explain': typeof ExplainRoute
  '/explore': typeof ExploreRoute
  '/facts': typeof FactsRoute
  '/food': typeof FoodRoute
  '/food-labels': typeof FoodLabelsRoute
  '/grey-market': typeof GreyMarketRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/emergency': typeof EmergencyRoute
  '/explain': typeof ExplainRoute
  '/explore': typeof ExploreRoute
  '/facts': typeof FactsRoute
  '/food': typeof FoodRoute
  '/food-labels': typeof FoodLabelsRoute
  '/grey-market': typeof GreyMarketRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/emergency'
    | '/explain'
    | '/explore'
    | '/facts'
    | '/food'
    | '/food-labels'
    | '/grey-market'
    | '/library'
    | '/onboarding'
    | '/privacy'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/emergency'
    | '/explain'
    | '/explore'
    | '/facts'
    | '/food'
    | '/food-labels'
    | '/grey-market'
    | '/library'
    | '/onboarding'
    | '/privacy'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/emergency'
    | '/explain'
    | '/explore'
    | '/facts'
    | '/food'
    | '/food-labels'
    | '/grey-market'
    | '/library'
    | '/onboarding'
    | '/privacy'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EmergencyRoute: typeof EmergencyRoute
  ExplainRoute: typeof ExplainRoute
  ExploreRoute: typeof ExploreRoute
  FactsRoute: typeof FactsRoute
  FoodRoute: typeof FoodRoute
  FoodLabelsRoute: typeof FoodLabelsRoute
  GreyMarketRoute: typeof GreyMarketRoute
  LibraryRoute: typeof LibraryRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain': {
      id: '/explain'
      path: '/explain'
      fullPath: '/explain'
      preLoaderRoute: typeof ExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facts': {
      id: '/facts'
      path: '/facts'
      fullPath: '/facts'
      preLoaderRoute: typeof FactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-labels': {
      id: '/food-labels'
      path: '/food-labels'
      fullPath: '/food-labels'
      preLoaderRoute: typeof FoodLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grey-market': {
      id: '/grey-market'
      path: '/grey-market'
      fullPath: '/grey-market'
      preLoaderRoute: typeof GreyMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EmergencyRoute: EmergencyRoute,
  ExplainRoute: ExplainRoute,
  ExploreRoute: ExploreRoute,
  FactsRoute: FactsRoute,
  FoodRoute: FoodRoute,
  FoodLabelsRoute: FoodLabelsRoute,
  GreyMarketRoute: GreyMarketRoute,
  LibraryRoute: LibraryRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
